- build/infrastructure/main/locals.tf
- build/infrastructure/main/outputs.tf
> added change requested by dbjorgensen

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202202081107 ChangeVoltActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202202081140 AddBatmanActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202202081157 AddBatmanGridAreas.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202202081213 AddBatmanGridAreaLinks.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202202081107 ChangeVoltActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202202081140 AddBatmanActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202202081157 AddBatmanGridAreas.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202202081213 AddBatmanGridAreaLinks.sql
Updates some test-actor data for Volt and Batman
> Update data in Actor Registry

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202203031046 Add KMD2 to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202203031047 Add KMD2 to GridArea Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202203031048 Add KMD2 to GridAreaLink Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202203031046 Add KMD2 to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202203031047 Add KMD2 to GridArea Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202203031048 Add KMD2 to GridAreaLink Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202203031046 Add KMD2 to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202203031047 Add KMD2 to GridArea Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202203031048 Add KMD2 to GridAreaLink Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202203031046 Add KMD2 to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202203031047 Add KMD2 to GridArea Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202203031048 Add KMD2 to GridAreaLink Table.sql
Adds new Actors with their associated GridAreas and links to the Actor Registry
> Added new KMD Actors with GridAreas

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202203151344 Add Test Actors.sql
> Removed actors that apparently where created.

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202203151344 Add Test Actors.sql
There were more actors that already existed
> Remove more actors

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202203231414 FixEDActorGLN.sql
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Startup.cs
> Update GLN for ED Actor

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202203231453 RemoveDDQFromTestActors.sql
> Remove DDQ from roles for test-actors

- build/infrastructure/main/app-webapi.tf
Fix for incorrect config value in terraform
> Change terraform appsetting value

- build/infrastructure/main/app-webapi.tf
> Fix missing config values

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202204040929 Add New actors to ActorInfo Table.sql
> Add new actors

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202204040929 Add New actors to ActorInfo Table.sql
> Fix Spelling error

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202204040929 Add New actors to ActorInfo Table.sql
> Fix identity insert problem

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Model/202204051318 Alter Address Columns for Organization.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Model/202204051318 Alter Address Columns for Organization.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202204051318 Alter Address Columns for Organization.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Model/202204051318 Alter Address Columns for Organization.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Model/202204051318 Alter Address Columns for Organization.sql
> Change default and not null for columns

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202204060911 Add More New Actors to ActorInfo Table.sql
> Add More Actors and GridAreas

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202204061443 Add Missing GridAreas to GridAreaLink Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202204061443 Add Missing GridAreas to GridAreaLink Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202204061443 Add Missing GridAreas to GridAreaLink Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202204061443 Add Missing GridAreas to GridAreaLink Table.sql
Add some missing GridArea Links
> Add Missing GridAreaLinks

- build/infrastructure/main/app-webapi.tf
- build/infrastructure/main/func-organization.tf
- build/infrastructure/main/kv-shared-resources.tf
Use shared app service plan.
Use app service module.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/262
> Use shared plan and module

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202204211433 Add New actors to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202204211434 Add More New Actors to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202204211433 Add New actors to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202204211434 Add More New Actors to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202204211433 Add New actors to ActorInfo Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202204211434 Add More New Actors to ActorInfo Table.sql
> More Actors to all environments

- source/Energinet.DataHub.MarketParticipant.Integration.Model/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Dtos/GridAreaUpdatedIntegrationEvent.cs
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Energinet.DataHub.MarketParticipant.Integration.Model.csproj
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Parsers/GridAreaUpdatedIntegrationEventParser.cs
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Protobuf/GridAreaUpdatedIntegrationEventContract.proto
- source/Energinet.DataHub.MarketParticipant.Libraries.Tests/Parsers/GridAreaUpdatedIntegrationEventParserTests.cs
- wordlist.txt
> Added GridAreaLinkId To Model

- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Energinet.DataHub.MarketParticipant.Integration.Model.csproj
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Parsers/ActorUpdatedIntegrationEventParser.cs
> actor parser updated

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205041047 AddDDQTOBatmanActorsU001.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205041047 AddDDQTOBatmanActorsU001.sql
> Change roles for Batman Actor in test env.

- source/Energinet.DataHub.MarketParticipant.Application/Commands/Actor/ActorDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Commands/Actor/ChangeActorDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Commands/Actor/CreateActorDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/Actor/CreateActorHandler.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/Actor/UpdateActorHandler.cs
- source/Energinet.DataHub.MarketParticipant.Application/Mappers/OrganizationMapper.cs
- source/Energinet.DataHub.MarketParticipant.Application/Validation/CreateActorCommandRuleSet.cs
- source/Energinet.DataHub.MarketParticipant.Application/Validation/Rules/MeteringPointTypeValidationRule.cs
- source/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateActorCommandRuleSet.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Handlers/CreateActorHandlerTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Handlers/UpdateActorHandlerTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Validation/CreateActorCommandRuleSetTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Validation/UpdateActorCommandRuleSetTests.cs
changed metering point type dto to string
* #0000
> changed metering point type dto to string

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202205161321 ChangeEllevActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205161321 ChangeEllevActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205161332 FixGLNOnActors.sql
> Fix errors in script files

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202205180816 AddChangeBatmanAndVoltActorsWithIds.sql
> Update Actors and Create Actors on B-001

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202205181300 Add New GridAreas for Test.sql
> Add new grid areas for B-001 test

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205181259 AddChangeBatmanAndVoltActorsWithIds.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205181300 Add New GridAreas for Test.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205181200 Migrate GridArea to Actor.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205181259 AddChangeBatmanAndVoltActorsWithIds.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205181300 Add New GridAreas for Test.sql
> Add new test actors to T and U env

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205181259 AddChangeBatmanAndVoltActorsWithIds.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205181259 AddChangeBatmanAndVoltActorsWithIds.sql
> Fix Problem with Test Actors on T and U

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202205251026 ReverseChangeEllevActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205251026 ReverseChangeEllevActors.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205251014 ChangeEllevActors.sql
> Fix so that it's in sync with b002

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Model/202204221002 Create GridAreaLinkNew Table.sql
> Add missing script

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202205311019 AddBatManDDQ.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202205311019 AddBatManDDQ.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205311019 AddBatManDDQ.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205311019 AddBatManDDQ.sql
> Update roles on batman actors, add new actor for DDQ

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205311019 AddBatManDDQFromT.sql
> Add Actor from T to U for Batman

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205311112 UpdateActorRoles.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202205311113 UpdateGLN.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205311112 UpdateActorRoles.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202205311113 UpdateGLN.sql
Various script changes to actors
> Various updates

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202206071354 UpdateGLNForEg.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202206071354 UpdateGLNForEg.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202206071354 UpdateGLNForEg.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202206071354 UpdateGLNForEg.sql
> Change wrong GLN

- build/infrastructure/main/app-webapi.tf
- build/infrastructure/main/func-organization.tf
- build/infrastructure/main/kv-shared-access-policy.tf
- build/infrastructure/main/kv-shared-resources.tf
> added keyvault references

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202206201116 UpdateTitansActorRoles.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202206201116 UpdateTitansActorRoles.sql
> Remove wrong role combinations for Titans Actor

- source/Energinet.DataHub.MarketParticipant.Domain/Services/ActorIntegrationEventsQueueService.cs
Updated existing event to use the data from the new structure
> Flatten data

- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Startup.cs
> add app insights

- source/Energinet.DataHub.MarketParticipant.Infrastructure/Energinet.DataHub.MarketParticipant.Infrastructure.csproj
integration model package upgrade to 2.3.0
* #0000
> integration model package upgrade to 2.3.0

- source/Energinet.DataHub.MarketParticipant.Application/Services/OrganizationIntegrationEventsHelperService.cs
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Energinet.DataHub.MarketParticipant.Infrastructure.csproj
created integration mapping, status
* #0000
> created integration mapping, status

- source/Energinet.DataHub.MarketParticipant.Application/Handlers/Organization/UpdateOrganizationHandler.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Services/IUniqueOrganizationBusinessRegisterIdentifierService.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Services/OrganizationFactoryService.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Services/UniqueOrganizationBusinessRegisterIdentifierService.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Services/UniqueOrganizationBusinessRegisterIdentifierServiceTests.cs
business register identifier fix, now ignores own org
* #0000
> business register identifier fix, now ignores own org

- source/Energinet.DataHub.MarketParticipant.Application/Mappers/OrganizationMapper.cs
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Energinet.DataHub.MarketParticipant.Infrastructure.csproj
re adding MP types mapping
* #0000
> re adding MP types mapping

- source/Energinet.DataHub.MarketParticipant.Domain/Energinet.DataHub.MarketParticipant.Domain.csproj
- source/Energinet.DataHub.MarketParticipant.Domain/Model/IntegrationEvents/ActorIntegrationEvents/ActorContactEventData.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Model/IntegrationEvents/ActorIntegrationEvents/MeteringPointTypeAddedToActorIntegrationEvent.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Model/IntegrationEvents/ActorIntegrationEvents/MeteringPointTypeRemovedFromActorIntegrationEvent.cs
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Energinet.DataHub.MarketParticipant.Infrastructure.csproj
Fix for problem with deserializing meterintpoint type
> Fix for deserializing problem

- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/IMarketParticipantGridAreaClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantGridAreaClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/ChangeGridAreaDto.cs
Adding grid name update in client
* #0000
> Adding grid name update client

- source/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateGridAreaCommandRuleSet.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Validation/UpdateGridAreaCommandRuleSetTests.cs
Updated validation for gridarea name change
* #0000
> Updated validation for gridarea name change

- .github/workflows/ci.yml
> add missing parameter to ci.yml

- .github/workflows/cd.yml
> merge workflows introduced in pr #258

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Helpers/CustomScriptProvider.cs
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Helpers/DefaultUpgrader.cs
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Helpers/ResultReporter.cs
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Helpers/SqlAppAuthenticationProvider.cs
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Helpers/UpgradeFactory.cs
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Program.cs
Ref: https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/661
> Replace DbUp with DbUp.Reboot

- source/Energinet.DataHub.MarketParticipant.Application/Commands/User/GetAssociatedUserActorsCommand.cs
- source/Energinet.DataHub.MarketParticipant.Application/Commands/User/GetAssociatedUserActorsResponse.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/User/GetAssociatedUserActorsHandler.cs
- source/Energinet.DataHub.MarketParticipant.Application/Validation/GetAssociatedUserActorsCommandRuleSet.cs
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/IMarketParticipantUserClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/ITokenClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantUserClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/GetAssociatedUserActorsResponseDto.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/TokenClient.cs
- source/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserController.cs
- source/Energinet.DataHub.MarketParticipant.Libraries.Tests/Clients/MarketParticipantClientTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Handlers/GetAssociatedUserActorsHandlerTests.cs
> get user actors init

- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/TokenController.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Startup.cs
> signingkey cache onstartup

- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorContactController.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorController.cs
> Added permissions for ActorManage

- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorContactUnsafeController.cs
Added unsafe controller for actor contacts since they are now protected with permissions in the normal controller.
> Added ActorContact Unsafe controller

- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Common/DbTestHelper.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/UpdateUserRoleTemplatesIntegrationTests.cs
to ensure update doesn't remove other actors assignments
> Added an extra unit test

- source/Energinet.DataHub.MarketParticipant.Domain/Model/EmailAddress.cs
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserOverviewRepository.cs
> Adding order to search and get user

- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/IMarketParticipantUserRoleClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantUserRoleClient.cs
client userroles return type update
* #0000
> client userroles return type update

- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Common/DbTestHelper.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/GetUserRolesAllIntegrationTests.cs
adding test for get all user roles
* #0000
> adding test for get all user roles

- source/Energinet.DataHub.MarketParticipant.Application/Commands/UserRoles/UserRoleWithPermissionsDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/UserRoles/GetUserRoleHandler.cs
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/IMarketParticipantUserRoleClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantUserRoleClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/UserRoleWithPermissionsDto.cs
adding new UserRoleDto with permissions
* #0000
> adding new UserRoleDto with permissions

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Model/202301161014 Add UserRoleAuditLog Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Model/202301161014 Add UserRoleAuditLog Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Model/202301161014 Add UserRoleAuditLog Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Model/202301161014 Add UserRoleAuditLog Table.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-002/Model/202301161014 Add UserRoleAuditLog Table.sql
added environment scripts user role audit logs
* #0000
> added environment scripts user role audit logs

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Remove unused secrets.
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/720
> Cleanup in secrets

- .github/workflows/publish-marketparticipant-client.yml
- .github/workflows/publish-marketparticipant-model.yml
> add allow merge to nuget

- .github/workflows/publish-marketparticipant-client.yml
- .github/workflows/publish-marketparticipant-model.yml
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Integration.Model/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Energinet.DataHub.MarketParticipant.Integration.Model.csproj
> Compare ==

- source/Energinet.DataHub.MarketParticipant.Application/Commands/UserRoles/CreateUserRoleDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/UserRoles/CreateUserRoleHandler.cs
- source/Energinet.DataHub.MarketParticipant.Application/Validation/CreateUserRoleCommandRuleSet.cs
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/CreateUserRoleDto.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserController.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserRoleController.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/UserRoleAuditLogIntegrationTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Handlers/CreateUserRoleHandlerTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Validation/CreateUserRoleCommandRuleSetTests.cs
- wordlist.txt
Changed type of permissions in DTO to ints
> Updated createRoleDto to use int for permissions

- source/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserRoleRepository.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Common/DbTestHelper.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/GetUserRolesAllIntegrationTests.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/UpdateUserRoleIntegrationTests.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/UserRoleAuditLogIntegrationTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Handlers/UpdateUserRoleHandlerTests.cs
tests for update user role update
* #0000
> tests for update user role update

- source/Energinet.DataHub.MarketParticipant.Application/Energinet.DataHub.MarketParticipant.Application.csproj
- source/Energinet.DataHub.MarketParticipant.Common/Energinet.DataHub.MarketParticipant.Common.csproj
- source/Energinet.DataHub.MarketParticipant.Domain/Energinet.DataHub.MarketParticipant.Domain.csproj
- source/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/Energinet.DataHub.MarketParticipant.EntryPoint.Organization.csproj
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserRoleController.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi.csproj
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Energinet.DataHub.MarketParticipant.Infrastructure.csproj
> Updated permission for create and edit userrole

- source/Energinet.DataHub.MarketParticipant.Application/Commands/UserRoles/UserRoleWithPermissionsDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/UserRoles/GetUserRoleHandler.cs
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/UserRoleWithPermissionsDto.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/UpdateUserRoleIntegrationTests.cs
updating user role permission list from string to int
* #0000
> updating user role permission to list type

- source/Energinet.DataHub.MarketParticipant.Application/Services/UserRoleAuditLogService.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Model/Users/UserRoleAuditLogSerialized.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Services/UserRoleAuditLogServiceTests.cs
user role audit log permission type change
* #0000
> user role audit log permission type change

- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-001/Seed/202302141300 Add More Permission To Eic.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/B-002/Seed/202302141300 Add More Permission To Eic.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202302141300 Add More Permission To Eic.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/T-001/Seed/202302141300 Add More Permission To Eic.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-001/Seed/202302141300 Add More Permission To Eic.sql
- source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/U-002/Seed/202302141300 Add More Permission To Eic.sql
> Updated permissions to Eics 

- source/Energinet.DataHub.MarketParticipant.Application/Handlers/User/InviteUserHandler.cs
- source/Energinet.DataHub.MarketParticipant.Application/Services/IOrganizationDomainValidationService.cs
- source/Energinet.DataHub.MarketParticipant.Application/Services/OrganizationDomainValidationService.cs
- source/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Services/OrganizationDomainValidationServiceTests.cs
Organization domain validation on user invites
* #0000
> Organization domain validation on user invites

- source/Energinet.DataHub.MarketParticipant.Application/Services/SendGridEmailSender.cs
- source/Energinet.DataHub.MarketParticipant.Common/Configuration/Settings.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/Email/EmailSenderRegistration.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/local.settings.sample.json
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/OrganizationIntegrationTestHost.cs
adding bcc for send grid emails at user invites
* #0000
> adding bcc for send grid emails

- source/Energinet.DataHub.MarketParticipant.Domain/Services/UserInvitationService.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Services/UserInvitationServiceTests.cs
bug fix user invite role assignments
* #0000
> bug fix user invite role assignments

- .github/workflows/publish-marketparticipant-client.yml
- .github/workflows/publish-marketparticipant-model.yml
- source/Energinet.DataHub.MarketParticipant.Application/Commands/Permissions/PermissionDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/Permissions/GetPermissionsHandler.cs
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/PermissionDetailsDto.cs
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2CRolesProvider.cs
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Energinet.DataHub.MarketParticipant.Integration.Model.csproj
adding permission created to response dto
* #0000
> adding permission created to response

- source/Energinet.DataHub.MarketParticipant.Application/Commands/UserRoles/PermissionDetailsDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Commands/UserRoles/UserRoleWithPermissionsDto.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/UserRoles/GetPermissionDetailsHandler.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/UserRoles/GetUserRoleHandler.cs
adding created to permission details
* #0000
> adding created to permission details

- source/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
> rule set registration

- source/Energinet.DataHub.MarketParticipant.Application/Commands/UserRoles/GetUserRolesToPermissionCommand.cs
- source/Energinet.DataHub.MarketParticipant.Application/Commands/UserRoles/GetUserRolesToPermissionResponse.cs
- source/Energinet.DataHub.MarketParticipant.Application/Handlers/UserRoles/GetUserRolesToPermissionHandler.cs
- source/Energinet.DataHub.MarketParticipant.Application/Validation/GetUserRolesToPermissionCommandRuleSet.cs
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/IMarketParticipantUserRoleClient.cs
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantUserRoleClient.cs
- source/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Repositories/IPermissionAuditLogEntryRepository.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Repositories/IUserOverviewRepository.cs
- source/Energinet.DataHub.MarketParticipant.Domain/Repositories/IUserRoleRepository.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorController.cs
- source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserRoleController.cs
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserRoleRepository.cs
- source/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/GetUserRolesToPermissionIntegrationTests.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Handlers/GetUserRoleToPermissionHandlerTest.cs
- source/Energinet.DataHub.MarketParticipant.Tests/Validation/GetUserRolesToPermissionCommandRuleSetTests.cs
A new endpoint has been added, that will return all user roles that have a given permission assigned.
> Add endpoint to recieve userroles to a given permission

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/detect-changes.yml
- .github/workflows/publish-marketparticipant-client.yml
- .github/workflows/publish-marketparticipant-model.yml
- source/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/Energinet.DataHub.MarketParticipant.Integration.Model/documents/release-notes/release-notes.md
- source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Energinet.DataHub.MarketParticipant.Integration.Model.csproj
After the introduction of ci-orchestrator this is no longer needed
> remove allow_merge

- source/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
Add new permission to use for settlements
> Add new settlements manage permission

- source/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserIdentityRepository.cs
adding missing selector in SearchUserIdentitiesAsync
* #0000
> adding missing selector in SearchUserIdentitiesAsync

- source/Energinet.DataHub.MarketParticipant.Infrastructure/Energinet.DataHub.MarketParticipant.Infrastructure.csproj
> Update alpha package

- source/api-client/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/IMarketParticipantUserClient.cs
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantClient.cs
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantUserClient.cs
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/UserIdentityUpdateDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/User/UpdateUserIdentityCommand.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/User/UserIdentityUpdateDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/UpdateUserIdentityHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateUserIdentityCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Repositories/IUserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Repositories/UserIdentityRepositoryTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Handlers/UpdateUserIdentityHandlerTests.cs
Updates user identity phone numner  in azure ad b2c with graph
* #0000
> Phone number update identity azure

- .github/workflows/cd.yml
- .github/workflows/codeql.yml
> move codeql cd trigger to cd.yml

- .github/workflows/cd.yml
> remove dotnet coverage report upload on cd

- source/api-client/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/UserIdentityUpdateDto.cs
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/UserOverviewItemDto.cs
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Models/UserOverviewSortProperty.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Query/User/UserOverviewItemDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Query/User/UserOverviewSortProperty.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/User/UserIdentityUpdateDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/GetUserOverviewHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/UpdateUserIdentityHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateUserIdentityCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Users/UserIdentity.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Users/UserOverviewItem.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Users/UserOverviewSortProperty.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Repositories/IUserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserOverviewRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Repositories/UserIdentityRepositoryTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Handlers/UpdateUserIdentityHandlerTests.cs
> feat: useroverview - full name replaced by first and last name

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
- .github/workflows/publish-marketparticipant-client.yml
- source/api-client/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1141
> Bump use of GitHub actions/workflows to v11

- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/Startup.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserRepository.cs
missing function registration
* #0000
> missing function registration

- source/api-client/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/IMarketParticipantUserInvitationClient.cs
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/MarketParticipantUserInvitationClient.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/User/ReInviteUserCommand.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/ReInviteUserHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/ReInviteUserCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Users/User.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Repositories/IUserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Services/IUserInvitationService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Services/UserInvitationService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/InvitationController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Services/UserInvitationServiceTests.cs
> Reinvite flow

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Services/UserInvitationService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Services/UserInvitationServiceTests.cs
added tests and fixed todo
* #0000
> added tests and fixed todo

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
- .github/workflows/publish-marketparticipant-client.yml
- source/api-client/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1251
> bumped to v12 in .github

- .github/workflows/ci-dotnet.yml
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1093
> Use new integration test env

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
The permission settlements:manage was split in two:
- settlement-reports:manage
- calculations:manage 
ADR 105
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/979
> Added new permissions.

- .github/workflows/ci-dotnet.yml
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1201
> New tenant variable

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Energinet.DataHub.MarketParticipant.Application.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/Energinet.DataHub.MarketParticipant.Common.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/Energinet.DataHub.MarketParticipant.EntryPoint.Organization.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Properties/launchSettings.json
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1383
> Health check response

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Energinet.DataHub.MarketParticipant.Application.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/Energinet.DataHub.MarketParticipant.Common.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/Energinet.DataHub.MarketParticipant.EntryPoint.Organization.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi.csproj
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1435
> Bump App package

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/PREPROD-001/Seed/202310031530 Patch Energinet Bootstrap.sql
> Add God user for preprod_001

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
> new permission for requesting aggregated measured data

- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/GridAreaController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/GridAreaOverviewController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/TokenController.cs
> GridArea and Token webapi return types updated

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Query/User/ActorDisplayNameDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Query/User/AssignedActorDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/GetUserOverviewHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Startup.cs
Dto renaming for swagger generation 
* #0000
> Dto renaming for swagger generation 

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Query/User/AssignedActorDto.cs
> prop name change

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Energinet.DataHub.MarketParticipant.Application.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Services/CertificateService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Startup.cs
> changed CertificateClient to SecretClient for KeyVault communication

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Actor/ActorMarketRoleDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Mappers/MarketRoleMapper.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Mappers/OrganizationMapper.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/CreateActorCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateActorCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Handlers/CreateActorHandlerTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Validation/CreateActorCommandRuleSetTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Validation/UpdateActorCommandRuleSetTests.cs
> Replaced string with eic function enum

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateActorCommandRuleSet.cs
> Added update for ruleset update actor

- .github/workflows/ci-dotnet.yml
- .github/workflows/publish-marketparticipant-client.yml
- source/api-client/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1813
> Remove Codecov flags

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/SANDBOX-002/Seed/202401171620 Insert Grid Area for EDI subsystem tests.sql
> feat: added grid area 804 to s-002 for edi subsystem tests

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202401221000 Alter UsedActorCertificates Table.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202401221000 Alter UsedActorCertificates Table.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/EntityConfiguration/ActorEntityConfiguration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Model/ActorEntity.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Model/UsedActorCertificatesEntity.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/ActorRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Repositories/ActorRepositoryTests.cs
> added actor id to used certificates table and code updates

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202401221000 Alter UsedActorCertificates Table.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202401221000 Alter UsedActorCertificates Table.sql
> script update

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202401221000 Alter UsedActorCertificates Table.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202401221000 Alter UsedActorCertificates Table.sql
> script update used certificates

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/InviteConfig.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Services/SendGridEmailSender.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/Configuration/Settings.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/Email/InviteConfigRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/local.settings.sample.json
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/OrganizationIntegrationTestHost.cs
> email update with environment information

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/User/GetUserProfileCommand.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/User/GetUserProfileResponse.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/User/UserProfileUpdateDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/GetUserProfileHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/GetUserProfileCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserController.cs
init datatypes and flow for user profile endpoints 
* #0000
> init datatypes and flow

- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserController.cs
> user profile update change

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/GetUserProfileHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/GetUserProfileHandlerIntegrationTests.cs
get userprofile handler and tests
* #0000
> get userprofile handler and tests

- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Security/ControllerAuthorizationTests.cs
> auth fix user profile

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Services/PermissionRelationServiceTest.cs
added actor-master-data:manage permission
* #0000
> added actor-master-data:manage permission

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Actor/UpdateActorNameCommand.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/Actor/UpdateActorNameHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateActorNameCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorContactController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/UpdateActorNameHandlerIntegrationTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Common/TestPreparationModels.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Handlers/UpdateActorNameHandlerTests.cs
> added flow for actor name change

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
missing marketrole and permission setup
* #0000
> missing marketrole and permission setup

- .github/workflows/codeql.yml
- .github/workflows/detect-changes.yml
Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1911
> Bump versions to remove Node16 warnings

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
- .github/workflows/publish-marketparticipant-client.yml
- source/api-client/Energinet.DataHub.MarketParticipant.Client/documents/release-notes/release-notes.md
- source/api-client/Energinet.DataHub.MarketParticipant.Client/source/Energinet.DataHub.MarketParticipant.Client/Energinet.DataHub.MarketParticipant.Client.csproj
Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1879
> Update .github refs to v13

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Energinet.DataHub.MarketParticipant.Application.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Services/EmailContentGeneratorTests.cs
> missing email template

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Delegations/UpdateActorDelegationCommand.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Delegations/UpdateActorDelegationDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/Delegations/UpdateActorDelegationResponse.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/Delegations/UpdateDelegationForActorHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/UpdateDelegationForActorCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/RepositoryRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Delegations/ActorDelegation.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Repositories/IActorDelegationRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/ActorDelegationRepository.cs
> init commit for update delegation

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Services/ActorFactoryService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Services/ActorFactoryServiceTests.cs
> feat: delegation - added allowed market roles check actor factory

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Handlers/GetPermissionRelationsHandlerTests.cs
> unit test permission relation handler

- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/CheckEmailExistsHandlerIntegrationTests.cs
> test added

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/BalanceResponsible/BalanceResponsibleDto.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/BalanceResponsible/GetBalanceResponsiblesForActorCommand.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Commands/BalanceResponsible/GetBalanceResponsiblesForActorResponse.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/BalanceResponsible/GetBalanceResponsiblesForActorHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/GetBalanceResponsiblesForActorCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/ApplicationServiceRegistration.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorController.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/GetBalanceResponsibleForActorHandlerIntegrationTests.cs
> webapi and handler for BalanceResponsible

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
EDI have to support wholesale settlement request from the UI. Hence the user needs the right to do so.
* #0000
> feat: add request wholesale settlement right

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/ActiveDirectory/CvrRegisterRegistrations.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/Configuration/Settings.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Common/Options/CvrRegisterOptions.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization/Extensions/DependencyInjection/ApimCertificateStoreExtensions.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization/Extensions/DependencyInjection/HttpClientExtensions.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization/Options/CertificateSynchronizationOptions.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization/Program.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization/local.settings.sample.json
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.LocalWebApi/sample.local-webapi.appsettings.json
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/local.settings.sample.json
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/sample.appsettings.json
> chore: ioptions pattern markpart - cvr register and certificate synchronization options

- .github/workflows/cd.yml
> Titans --> Raccoons

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202406131315 Extended TemplateParameters.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202406131315 Extended TemplateParameters.sql
> fix: Extend length of template params.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
Reverts Energinet-DataHub/geh-market-participant#903
> Revert "Limit settlement report to fas."

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Validation/CreateActorContactCommandRuleSet.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202406201400 Extended PhoneNumber for Contacts.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202406201400 Extended PhoneNumber for Contacts.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/CreateActorContactHandlerIntegrationTests.cs
> fix: Phone number for contacts is too short.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserIdentityRepository.cs
> fix: reuse error code for invalid phone

- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserRoleController.cs
> fix: Allow permission to role overview for actors.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/PREPROD-001/Seed/202407041300 Link missing grid areas.sql
> chore: markpart - assigning missing grid area owners - preprod

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActorClientSecretService.cs
> Extend certification duration to 1 year.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/Users/DeactivateUserHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/Users/UserInvitationExpiredHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Repositories/IUserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.LocalWebApi/InMemoryUserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserIdentityRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/Organization/UserInvitationExpiredIntegrationTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/DeactivateUserTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Repositories/UserIdentityRepositoryTests.cs
> Disabling user now also removes MitId.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
> Add request-aggregated-measured-data:view to Grid Access Provider.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/PREPROD-001/Seed/202407181330 Insert Grid Area.sql
> Add grid area 906 to preprod.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Common/AzureCredentialsProvider.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Common/TestConfigurationProvider.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Fixtures/ActorClientSecretFixture.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Fixtures/B2CFixture.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Fixtures/CertificateFixture.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Fixtures/GraphServiceClientFixture.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Fixtures/KeyClientFixture.cs
> Improve performance of tests.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Services/UserIdentityOpenIdLinkService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Fixtures/GraphServiceClientFixture.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/TokenControllerIntegrationTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Services/UserIdentityOpenIdLinkServiceTests.cs
> fix: Inactive user gets MitId linked.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/PREPROD-001/Seed/202408021345 Link missing grid areas.sql
Still need to verify that provided grid areas + grid access provider is correct.
> Add missing grid areas.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
Wholesale needed a new view permission, this implements it backend, another PR for the frontend will be added later to actually use it.
> Added new permission

- .github/workflows/cd.yml
- .github/workflows/ci-orchestrator.yml
- .github/workflows/detect-changes.yml
Add conditional deployment to mark part:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2245
> conditional deployment mark part

- .github/workflows/cd.yml
> fix mark part

- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/ActorController.cs
It should only be possible to change the actors name with this permission
> Change permission to actor manage

- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.CertificateSynchronization/Program.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/Energinet.DataHub.MarketParticipant.EntryPoint.Organization.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.Organization/Program.cs
> Use AspNet package.

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202409241530 Remove Permission from Inactive Role.sql
- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/PREPROD-001/Seed/202409241530 Remove Permission from Inactive Role.sql
> remove permission from inactive user role

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/PREPROD-001/Seed/202410181340 Update Grid PriceArea.sql
> Update price area for newly added grid areas in preprod

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/OrganizationAuditLogRepository.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/GetOrganizationAuditLogsHandlerIntegrationTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Repositories/OrganizationAuditLogRepositoryTests.cs
> group organization domain audit logs by id

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/Actors/ConsolidateActorsHandler.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Services/ActorConsolidationService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/SubsystemInformation.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Services/ActorConsolidationServiceIntegrationTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Tests/Services/ActorConsolidationServiceTests.cs
This pull request includes several changes to the `ConsolidateActorsHandler` and related services to improve the actor consolidation process by adding revision logging and unit of work management. The most important changes include the introduction of `IRevisionLogClient` for logging, the addition of `IUnitOfWorkProvider` to manage transactions, and updates to the tests to accommodate these changes.
* [`ConsolidateActorsHandler.cs`](diffhunk://#diff-3b0dc7928ecb0b3d11cfe99685e26cf13e5cb7695e654a484ebd80ea795711edL20-R66): Introduced `IRevisionLogClient` to log consolidation activities and removed `IDomainEventRepository` and `IUnitOfWorkProvider` dependencies.
* [`ActorConsolidationService.cs`](diffhunk://#diff-a7d2dbddd4213e486f45b1ab8246448a0b0942b83ab58b0ffa257b8e957bf743R19): Added …
> Write consolidations to revlog.

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
Upgrade all GitHub workflow references from v13 to v14
> Update .github references to v14

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
> fix: Remove ez from request aggregated measure data

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
> Add permission for transaction import

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
> Removed unused permission

- source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/PROD-001/Seed/202503061400 Move merged actor.sql
> move actor to new organization

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
Add permission for `Missing measurements log`
* #0000
> feat(permissions): add missing measurements log

- docs/Energinet.DataHub.MarketParticipant.Authorization/release-notes/release-notes.md
- global.json
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Authorization/Energinet.DataHub.MarketParticipant.Authorization.csproj
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Authorization/Services/AuthorizationVerifyService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.AuthApi/Extensions/DependencyInjection/MarketParticipantAuthApiModuleExtensions.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.EntryPoint.AuthApi/Security/AuthorizationService.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Services/CreateSignatureRoleAuthorizationIntegrationTests.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/integrationtest.local.settings.sample.json
Added support for key rotation.
> 1204 key rotation

- source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Permissions/PermissionId.cs
- source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Model/Permissions/KnownPermissions.cs
> Add "additional-recipients:*" permissions
